# test/parser Makefile
#  - builds the parserize executable for printing parsed strings from stdin

OCAMLC = ocamlc
OBJS = ../../compiler/_build/parser.cmo ../../compiler/_build/scanner.cmo parserize.cmo
INCLUDES = -I ../../compiler/_build

default: parserize

all:
	cd ..; make all

parserize: $(OBJS)
	$(OCAMLC) $(INCLUDES) -o parserize $(OBJS)

%.cmo: %.ml
	$(OCAMLC) $(INCLUDES) -c $<

%.cmi: %.mli
	$(OCAMLC) $(INCLUDES) -c $<

.PHONY: clean
clean:
	rm -f parserize *.cmo *.cmi

# # Generated by ocamldep *.ml
# parserize.cmo: ../../compiler/_build/parser.cmi ../../compiler/_build/ast.cmi
# parserize.cmx: ../../compiler/_build/parser.cmi ../../compiler/_build/ast.cmi
